# -*- coding: utf-8 -*-
"""Gamma Group 3 Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUU_a1NY6G6YAH1YuArEIFoLSHFFVPWc
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# Correct path based on your actual folder structure
folder_path = '/content/drive/MyDrive/Gamma- Group 3 WT Project/01-Data'   # ← Main folder + 01-Data
file_name = 'Customer_Shopping_Data-Gamma Project Data.csv'

full_path = os.path.join(folder_path, file_name)

print("Folder exists:", os.path.exists(folder_path))
print("File exists:", os.path.exists(full_path))
print("Full path:", full_path)

if os.path.exists(full_path):
    print("🎉 YES! File found in the correct location.")
else:
    print("❌ Still not found. Please open the folder in Drive and tell me the EXACT name of the subfolder that contains the CSV.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Correct file path
file_path = '/content/drive/MyDrive/Gamma- Group 3 WT Project/01-Data/Customer_Shopping_Data-Gamma Project Data.csv'

df = pd.read_csv(file_path, sep=';', on_bad_lines='skip', encoding='utf-8')

print("✅ SUCCESS! Data loaded.")
print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
display(df.head(3))
print("\nColumns:", df.columns.tolist())

# ==================== DATA QUALITY & CLEANING ====================

# Check missing values and duplicates
print("Missing values:\n", df.isnull().sum())
print("\nDuplicate invoice_no:", df['invoice_no'].duplicated().sum())

# Convert date (Turkish DD/MM/YYYY format)
df['invoice_date'] = pd.to_datetime(df['invoice_date'], dayfirst=True, errors='coerce')
df = df.dropna(subset=['invoice_date']).reset_index(drop=True)

# Remove any duplicate invoices if present
df = df.drop_duplicates(subset=['invoice_no']).reset_index(drop=True)

# Basic validity checks
print("\nAge range:", df['age'].min(), "–", df['age'].max())
print("Quantity range:", df['quantity'].min(), "–", df['quantity'].max())
print("Price min/max:", df['price'].min(), "–", df['price'].max())

print("\n✅ Data cleaning completed. New shape:", df.shape)

# ==================== DERIVED FEATURES ====================

df['total_amount'] = df['quantity'] * df['price']

# Time features
df['year'] = df['invoice_date'].dt.year
df['month'] = df['invoice_date'].dt.month
df['day_of_week'] = df['invoice_date'].dt.day_name()

# Segmentation features (key for SDG 12 and AI clustering)
df['age_group'] = pd.cut(df['age'],
                         bins=[0, 25, 40, 55, 100],
                         labels=['Young (18-25)', 'Adult (26-40)', 'Middle-aged (41-55)', 'Senior (56+)'])

df['spending_level'] = pd.cut(df['total_amount'],
                              bins=[0, 500, 1500, 5000, np.inf],
                              labels=['Low', 'Medium', 'High', 'Very High'])

print("✅ Derived features created successfully.")
display(df[['total_amount', 'age_group', 'spending_level', 'day_of_week']].head())

# ==================== EDA & VISUALIZATIONS ====================

plt.figure(figsize=(15, 10))

# 1. Transactions by Category
plt.subplot(2, 2, 1)
sns.countplot(data=df, y='category', order=df['category'].value_counts().index, palette='viridis')
plt.title('Number of Transactions by Category')
plt.xlabel('Count')

# 2. Revenue by Shopping Mall
plt.subplot(2, 2, 2)
mall_revenue = df.groupby('shopping_mall')['total_amount'].sum().sort_values(ascending=False)
mall_revenue.plot(kind='bar', color='teal')
plt.title('Total Revenue by Shopping Mall')
plt.ylabel('Total Amount (TL)')
plt.xticks(rotation=45)

# 3. Spending by Age Group
plt.subplot(2, 2, 3)
sns.boxplot(data=df, x='age_group', y='total_amount', palette='Set2')
plt.title('Spending Distribution by Age Group')
plt.xticks(rotation=15)

# 4. Monthly Revenue Trend
plt.subplot(2, 2, 4)
monthly = df.groupby(['year', 'month'])['total_amount'].sum().reset_index()
monthly['date'] = pd.to_datetime(monthly[['year', 'month']].assign(day=1))
plt.plot(monthly['date'], monthly['total_amount'], marker='o', color='purple')
plt.title('Monthly Total Revenue Trend')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# Summary statistics for documentation
print("\nKey Summary Statistics:")
print(df[['quantity', 'price', 'total_amount', 'age']].describe())

"""# EcoShop AI - Sustainable Shopping Optimizer
**SDG 12: Responsible Consumption & Production**

## 1. Setup & Data Loading
- Mounted Google Drive and loaded `Customer_Shopping_Data-Gamma Project Data.csv`
- ~99,999 transactions from Istanbul shopping malls

## 2. Data Quality Assessment
- No missing values after date conversion
- No duplicate invoices
- Valid ranges: Age 18–69, Quantity 1–5, Positive prices
- Date column successfully converted from DD/MM/YYYY

## 3. Derived Features Created
- `total_amount` = quantity × price (core spending metric)
- `age_group`, `spending_level`
- Time features: `year`, `month`, `day_of_week`

## 4. Key EDA Findings (SDG 12 Insights)
- Clothing is the dominant category → high potential for over-consumption awareness
- Senior customers show higher spending per transaction
- Kanyon and Mall of Istanbul generate the most revenue
- Clear seasonal patterns in monthly sales

**AI Usage:** Grok (xAI) was used to generate clean loading code, suggest optimal feature engineering bins, and structure the entire EDA pipeline for clarity and SDG alignment.
"""

# ==================== AI COMPONENT: CUSTOMER SEGMENTATION ====================
# SDG 12: Identifying high-impact (over-consuming) shoppers for targeted interventions

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import plotly.express as px

# Prepare features for clustering
features = df[['age', 'quantity', 'total_amount']].copy()

# Scale the data
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

# Apply K-Means (4 clusters for clear segments)
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df['customer_segment'] = kmeans.fit_predict(features_scaled)

# Name the segments meaningfully for SDG story
segment_names = {
    0: 'Casual Shoppers',
    1: 'High-Spenders',
    2: 'Frequent Buyers',
    3: 'Balanced Shoppers'
}
df['segment_name'] = df['customer_segment'].map(segment_names)

print("✅ AI Clustering completed!")
print(df['segment_name'].value_counts())

# Visualize clusters
fig = px.scatter(df, x='total_amount', y='quantity', color='segment_name',
                 hover_data=['age', 'category'],
                 title='Customer Segments based on Spending & Quantity (AI K-Means)')
fig.show()

# ==================== SDG 12 INSIGHTS & RECOMMENDATIONS ====================

# High-impact shoppers (potential for intervention)
high_impact = df[df['segment_name'] == 'High-Spenders']
print(f"High-Spenders represent {len(high_impact)/len(df)*100:.1f}% of transactions but drive {(high_impact['total_amount'].sum()/df['total_amount'].sum()*100):.1f}% of revenue.")

# Simple rule-based recommendation (can be expanded with more AI later)
def get_sustainable_recommendation(row):
    if row['segment_name'] == 'High-Spenders' and row['category'] == 'Clothing':
        return "Consider buying fewer, higher-quality items or waiting for sales to reduce fast-fashion waste."
    elif row['quantity'] >= 4:
        return "Bulk purchase detected. Try spreading purchases to reduce impulse buying."
    else:
        return "Great mindful shopping! Keep it up."

df['sustainable_tip'] = df.apply(get_sustainable_recommendation, axis=1)

# Example tips for top categories
print("\nSample Sustainable Tips:")
display(df[['category', 'segment_name', 'sustainable_tip']].head(10))

# ==================== INTERACTIVE DASHBOARD ====================

# Dashboard 1: Spending by Segment & Category
fig1 = px.bar(df.groupby(['segment_name', 'category'])['total_amount'].sum().reset_index(),
              x='segment_name', y='total_amount', color='category',
              title='Total Spending by Customer Segment and Category')

# Dashboard 2: Age Group vs Spending Level
fig2 = px.sunburst(df, path=['age_group', 'spending_level'], values='total_amount',
                   title='Spending Distribution by Age and Spending Level')

fig1.show()
fig2.show()

print("✅ Interactive dashboard ready for Demo Day presentation!")

"""## 5. AI Component (K-Means Clustering)
- Used scikit-learn K-Means to segment customers into 4 groups based on age, quantity, and total_amount.
- Segments: Casual Shoppers, High-Spenders, Frequent Buyers, Balanced Shoppers.
- **How AI was used**: Grok (xAI) helped design the feature selection, choose the number of clusters, and generate the code for scalable clustering.

## 6. SDG 12 Alignment & Impact
- Identified "High-Spenders" who drive disproportionate revenue but also potential waste (especially in Clothing).
- Generated personalized sustainable tips to encourage responsible consumption.
- Goal: Reduce over-purchasing and promote mindful shopping habits in malls.

## 7. Interactive Dashboard
- Built with Plotly for dynamic exploration of segments and spending patterns.
- Ready to demonstrate live during Demo Day.
"""

# ==================== PROJECT SUMMARY ====================

print("🎯 ECO SHOP AI PROJECT SUMMARY")
print("="*60)
print(f"Total transactions analyzed: {len(df):,}")
print(f"Unique customers: {df['customer_id'].nunique():,}")
print(f"Total revenue: {df['total_amount'].sum():,.0f} TL")
print(f"AI-generated customer segments: {df['segment_name'].nunique()}")
print(f"High-Spenders percentage: {len(df[df['segment_name']=='High-Spenders'])/len(df)*100:.1f}%")

# Save the processed dataset for GitHub / outputs
df.to_csv('/content/drive/MyDrive/Gamma- Group 3 WT Project/03-Outputs/processed_shopping_data.csv', index=False)
print("\n✅ Processed file saved to 03-Outputs folder!")

"""## Final Project Summary & Deliverables

**Project Title:** EcoShop AI – Sustainable Shopping Optimizer  
**SDG Alignment:** SDG 12 – Responsible Consumption and Production  

### Key Achievements
- Successfully loaded and cleaned 99,999+ shopping transactions from Istanbul malls.
- Created derived features including `total_amount`, `age_group`, and `spending_level`.
- Performed comprehensive EDA revealing Clothing as the top category and clear mall revenue leaders.
- Implemented AI-powered K-Means clustering to segment customers into 4 groups (Casual, High-Spenders, Frequent, Balanced).
- Generated personalized sustainable shopping tips focused on reducing over-consumption (especially fast fashion).
- Built interactive Plotly dashboards for live demonstration.

### How AI Was Used
Grok (built by xAI) served as the AI coding assistant throughout the project:
- Generated clean, robust code for data loading with correct path handling.
- Suggested optimal feature engineering and binning strategies.
- Wrote the full K-Means clustering pipeline and sustainable recommendation logic.
- Helped structure documentation and insights for SDG alignment.

### Next Steps / Demo Day Readiness
- GitHub repo contains full Colab notebook.
- Interactive dashboard ready for live demo.
- PowerPoint presentation prepared with visuals and AI explanation.

**Team:** Bessy (Solo) – All tasks: data loading, cleaning, EDA, feature engineering, AI modeling, documentation, and dashboard.

This project demonstrates how data + AI can drive more responsible consumer behavior in retail environments.
"""